apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "watcher.fullname" . }}-role
rules:
- apiGroups:
  - watcher.io
  resources:
  - watchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.io
  resources:
  - watchers/finalizers
  verbs:
  - update
- apiGroups:
  - watcher.io
  resources:
  - watchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - watcher.io
  resources:
  - pools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.io
  resources:
  - pools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/resize
  verbs:
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
