apiVersion: watcher.io/v1
kind: Pool
metadata:
  name: etl
  namespace: airflow
spec:
  airflowPoolName: etl
  reconcileIntervalSeconds: 30
  scaleSignal: Scheduled
  defaultSlots: 128
  increasePercent: 5
  maxSlots: 1024
  mode: patch
  workload:
    namespace: spark-operator
    deploymentName: spark-operator-controller
    metric: CPU
    threshold: 500
